search_terms:
- ivermectin
- albendazole
- mebendazole
- nitazoxanide
- fenbendazole
- doxycycline
- azithromycin
- metronidazole
- rifaximin
- zopiclone
- eszopiclone
- pregabalin
- gabapentin
- testosterone gel
- testosterone
- testosterone cypionate
- testosterone enanthate
- testosterone propionate
- trenbolone
- nandrolone
- boldenone
- oxandrolone
- anavar
- winstrol
- dianabol
- sustanon
- clenbuterol
- shytomel
- liothyronine
- sildenafil
- tadalafil
- vardenafil
- avanafil
- kamagra
- minoxidil
- finasteride
- dutasteride
- isotretinoin
- accutane
- tretinoin
- modafinil
- hydroxychloroquine
- prednisolone
- niclosmide
- cenforce 100 mg
- vidalista 10 mg
- vidalista 20 mg
- iverguard 12 mg
- iverheal 12 mg
- amoxicillin
- amoxicillin and potasisium cv
- metformin
- amlodipine
- telmisartan
- testosign gel
- anastrozole
- naltraxone
exclude_terms: []
country:
- au
- australia
- us
- united states
- usa
- united states of america
- gb
- united kingdom
- uk
- great britain
- britain
- de
- germany
client_regions:
- AU
- US
- GB
- DE
whatsapp_enabled: false
whatsapp_waha_session: slot10
whatsapp_template: ''
whatsapp_max_per_hour: 20
whatsapp_min_delay_s: 25
whatsapp_stop_on_reply: false
indiamart_message_enabled: false
indiamart_message_template: ''
indiamart_message_max_per_day: 20
indiamart_message_min_delay_s: 30
max_run_minutes: 0
max_lead_age_seconds: 30
allow_unknown_age: false
debug_snapshot: true
prefer_api: false
quality_level: 50
min_member_months: 0
max_age_hours: 48
zero_second_only: false
require_mobile_available: true
require_email_verified: false
headless: false
max_verified_leads_per_cycle: 15
require_mobile_verified: false
require_email_available: true
require_whatsapp_available: false
