search_terms:
- ivermectin
- albendazole
- mebendazole
- nitazoxanide
- doxycycline
- azithromycin
- metronidazole
- rifaximin
- zopiclone
- eszopiclone
- pregabalin
- gabapentin
- carisoprodol
- tapentadol
- baclofen
- tizanidine
- testosterone
- testosterone cypionate
- testosterone enanthate
- testosterone propionate
- trenbolone
- nandrolone
- boldenone
- oxandrolone
- anavar
- winstrol
- dianabol
- sustanon
- semaglutide
- liraglutide
- tirzepatide
- retatrutide
- clenbuterol
- cytomel
- liothyronine
- sildenafil
- tadalafil
- vardenafil
- avanafil
- kamagra
- minoxidil
- finasteride
- dutasteride
- isotretinoin
- accutane
- tretinoin
- tenofovir
- modafinil
- armodafinil
- hydroxychloroquine
- dexamethasone
- prednisone
exclude_terms: []
country:
- au
- australia
- de
- germany
- us
- united states
- usa
- united states of america
- gb
- united kingdom
- uk
- great britain
- britain
client_regions:
- AU
- DE
- US
- GB
whatsapp_enabled: false
whatsapp_waha_session: slot02
whatsapp_template: ''
whatsapp_max_per_hour: 20
whatsapp_min_delay_s: 25
whatsapp_stop_on_reply: false
indiamart_message_enabled: false
indiamart_message_template: ''
indiamart_message_max_per_day: 20
indiamart_message_min_delay_s: 30
max_run_minutes: 0
max_lead_age_seconds: 30
allow_unknown_age: false
debug_snapshot: true
prefer_api: false
quality_level: 70
min_member_months: 0
max_age_hours: 48
zero_second_only: false
require_mobile_available: false
require_email_verified: false
recent_refresh_seconds: 2
recent_wait_ms: 1200
recent_wait_networkidle: false
top_card_only: true
top_card_count: 1
max_new_per_cycle: 1
headless: false
require_mobile_verified: false
require_email_available: false
require_whatsapp_available: false
max_verified_leads_per_cycle: 3
